### ISSUE TITLE
float bug

### ISSUE THREAD

**Issue by hisubbotin** [ikusmart/CanonicalEquation#1]
1) На моем компе заваливается 9 тестов, похоже c float проблемы, они вообще не парсятся.

2) `Math.Abs(s.Multiplier) > float.Epsilon` вот такой прием, конечно, интересный, но не работает нигде.

**Comment by ikusmart** [comment]
1. Странно, у меня на двух разных машинах все тесты проходили. Я посмотрю , в чем проблема может быть

2. Насчёт сравнения , ну скорее привычка из кода с расчетами очень мелкими, тут согласен, он избыточен, так как точность у нас не прыгает

**Comment by ikusmart** [comment]
@hisubbotin Фикс проблемы парсинга float залил (поправил парсинг  и добавил поддержку двух форматов чисел с плавающей запятой)
Причина довольно тупая - не учитывалась разность культур на клиентских машинах при парсинге числа и соответственно разность разделителей, чего на своих машинах и не наблюдал  благополучно :/
